config/routes.rb
BalcaoGcom::Application.routes.draw do
  resources :produtos

  root :to => "produtos#index"

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  
  validates_presence_of :nome
  validates_presence_of :preco
  validates_presence_of :dono
  validates_presence_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  def to_param
    "#{id}-#{nome}"
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/produtos_controller.rb
class ProdutosController < InheritedResources::Base
  
  respond_to :html, :js, :json, :xml
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BalcaoGcom</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/produtos/_form.html.haml
= semantic_form_for (@produto, :remote => true) do |f|  
  - f.inputs do
    = f.input :nome, :label => 'Nome'
    = f.input :preco, :label => 'Preco'
    = f.input :descricao, :label => 'Descricao'
    = f.input :status, :label => 'Status'
    = f.input :quantidade, :label => 'Quantidade'
    = f.input :dono, :label => 'Dono'
    = f.input :email, :label => 'Email'

  = f.buttons

app/views/produtos/create.js.erb
show_message("<%= escape_javascript(@produto.nome) %> incluido com sucesso");

app/views/produtos/destroy.js.erb
$("li[data-id=<%=@produto.id%>]").slideUp();

app/views/produtos/edit.html.haml
%h1 Editing produto

= render 'form'

= link_to 'Show', @produto
\|
= link_to 'Back', produtos_path

app/views/produtos/index.html.haml
%h1= t ".titulo"

%ul
  - @produtos.each do |produto|
    %li{:data=> {:id => produto.id }}
      = link_to produto.nome, produto
      = produto.preco
      %span= produto.descricao
      %p
        = link_to "excluir", produto, :method => :delete, :confirm => "deseja excluir ?", :remote => true


%br

= link_to 'New Produto', new_produto_path

app/views/produtos/new.html.haml
%h1 New produto

= render 'form'

= link_to 'Back', produtos_path

app/views/produtos/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @produto.nome
%p
  %b Preco:
  = @produto.preco
%p
  %b Descricao:
  = @produto.descricao
%p
  %b Status:
  = @produto.status
%p
  %b Quantidade:
  = @produto.quantidade
%p
  %b Dono:
  = @produto.dono
%p
  %b Email:
  = @produto.email

= link_to 'Edit', edit_produto_path(@produto)
\|
= link_to 'Back', produtos_path